const dataBanjir = [
    {
      tahun: 2020,
      kota: [
        {
          nama: "Jakarta",
          jumlah_kasus: 15,
          kerugian: "Rp 200 M",
          korban_jiwa: 10,
          frekuensi_banjir: 5,
          rumah_rusak: 1000,
        },
        {
          nama: "Bandung",
          jumlah_kasus: 8,
          kerugian: "Rp 100 M",
          korban_jiwa: 5,
          frekuensi_banjir: 3,
          rumah_rusak: 500,
        },
        {
          nama: "Surabaya",
          jumlah_kasus: 5,
          kerugian: "Rp 50 M",
          korban_jiwa: 3,
          frekuensi_banjir: 2,
          rumah_rusak: 300,
        },
        {
          nama: "Medan",
          jumlah_kasus: 7,
          kerugian: "Rp 70 M",
          korban_jiwa: 4,
          frekuensi_banjir: 3,
          rumah_rusak: 400,
        },
        {
          nama: "Makassar",
          jumlah_kasus: 4,
          kerugian: "Rp 30 M",
          korban_jiwa: 2,
          frekuensi_banjir: 1,
          rumah_rusak: 200,
        },
      ],
    },
    {
      tahun: 2021,
      kota: [
        {
          nama: "Jakarta",
          jumlah_kasus: 18,
          kerugian: "Rp 250 M",
          korban_jiwa: 12,
          frekuensi_banjir: 6,
          rumah_rusak: 1200,
        },
        {
          nama: "Bandung",
          jumlah_kasus: 10,
          kerugian: "Rp 120 M",
          korban_jiwa: 6,
          frekuensi_banjir: 4,
          rumah_rusak: 600,
        },
        {
          nama: "Surabaya",
          jumlah_kasus: 6,
          kerugian: "Rp 60 M",
          korban_jiwa: 4,
          frekuensi_banjir: 2,
          rumah_rusak: 400,
        },
        {
          nama: "Medan",
          jumlah_kasus: 9,
          kerugian: "Rp 80 M",
          korban_jiwa: 5,
          frekuensi_banjir: 3,
          rumah_rusak: 500,
        },
        {
          nama: "Makassar",
          jumlah_kasus: 5,
          kerugian: "Rp 40 M",
          korban_jiwa: 3,
          frekuensi_banjir: 2,
          rumah_rusak: 300,
        },
      ],
    },
    {
      tahun: 2022,
      kota: [
        {
          nama: "Jakarta",
          jumlah_kasus: 20,
          kerugian: "Rp 300 M",
          korban_jiwa: 15,
          frekuensi_banjir: 7,
          rumah_rusak: 1500,
        },
        {
          nama: "Bandung",
          jumlah_kasus: 12,
          kerugian: "Rp 140 M",
          korban_jiwa: 8,
          frekuensi_banjir: 5,
          rumah_rusak: 700,
        },
        {
          nama: "Surabaya",
          jumlah_kasus: 7,
          kerugian: "Rp 70 M",
          korban_jiwa: 5,
          frekuensi_banjir: 3,
          rumah_rusak: 500,
        },
        {
          nama: "Medan",
          jumlah_kasus: 10,
          kerugian: "Rp 90 M",
          korban_jiwa: 6,
          frekuensi_banjir: 4,
          rumah_rusak: 600,
        },
        {
          nama: "Makassar",
          jumlah_kasus: 6,
          kerugian: "Rp 50 M",
          korban_jiwa: 4,
          frekuensi_banjir: 2,
          rumah_rusak: 400,
        },
      ],
    },
    {
      tahun: 2023,
      kota: [
        {
          nama: "Jakarta",
          jumlah_kasus: 22,
          kerugian: "Rp 350 M",
          korban_jiwa: 18,
          frekuensi_banjir: 8,
          rumah_rusak: 1800,
        },
        {
          nama: "Bandung",
          jumlah_kasus: 15,
          kerugian: "Rp 160 M",
          korban_jiwa: 10,
          frekuensi_banjir: 6,
          rumah_rusak: 800,
        },
        {
          nama: "Surabaya",
          jumlah_kasus: 8,
          kerugian: "Rp 80 M",
          korban_jiwa: 6,
          frekuensi_banjir: 3,
          rumah_rusak: 600,
        },
        {
          nama: "Medan",
          jumlah_kasus: 12,
          kerugian: "Rp 100 M",
          korban_jiwa: 8,
          frekuensi_banjir: 4,
          rumah_rusak: 700,
        },
        {
          nama: "Makassar",
          jumlah_kasus: 7,
          kerugian: "Rp 60 M",
          korban_jiwa: 5,
          frekuensi_banjir: 2,
          rumah_rusak: 500,
        },
      ],
    },
    {
      tahun: 2024,
      kota: [
        {
          nama: "Jakarta",
          jumlah_kasus: 25,
          kerugian: "Rp 400 M",
          korban_jiwa: 20,
          frekuensi_banjir: 9,
          rumah_rusak: 2000,
        },
        {
          nama: "Bandung",
          jumlah_kasus: 17,
          kerugian: "Rp 180 M",
          korban_jiwa: 12,
          frekuensi_banjir: 7,
          rumah_rusak: 900,
        },
        {
          nama: "Surabaya",
          jumlah_kasus: 10,
          kerugian: "Rp 90 M",
          korban_jiwa: 7,
          frekuensi_banjir: 4,
          rumah_rusak: 700,
        },
        {
          nama: "Medan",
          jumlah_kasus: 14,
          kerugian: "Rp 110 M",
          korban_jiwa: 9,
          frekuensi_banjir: 5,
          rumah_rusak: 800,
        },
        {
          nama: "Makassar",
          jumlah_kasus: 8,
          kerugian: "Rp 70 M",
          korban_jiwa: 6,
          frekuensi_banjir: 3,
          rumah_rusak: 600,
        },
        {
          nama: "Semarang",
          jumlah_kasus: 5,
          kerugian: "Rp 50 M",
          korban_jiwa: 3,
          frekuensi_banjir: 2,
          rumah_rusak: 400,
        },
      ],
    },
  ];
  
  export default dataBanjir;